### PR TITLE
fixed some issues with ignoring and ABC RN data retreival

### PR DESCRIPTION
**Pull request by TomW1605**

### CODE REVIEW

**Comment by TomW1605** [comment]
hi @markcs, is this still in development?

**Comment by markcs** [comment]
@TomW1605 Sorry, I've been away and didn't take a PC with me.  I'll check and merge this if all okay.

Thanks for the contribution!

**Comment by TomW1605** [comment]
ok sorry to bother you i was just suprised as it looked like an active project (if repos look inactive i just make a fork and dont bother with a PR) but then nothing happend for almost 2 weeks.

**Comment by TomW1605** [comment]
there may be some coade style issues as i have never activly used perl befor, only very minor (single line) modifications to other peoples code.

**Pull request merged**
